### ISSUE TITLE
First Tile In Chain Has Wrong Orientation

### ISSUE THREAD

**Issue by CryptokidFH** [mclarkk/lifxlan#118]
As title states, when running any example code on my tiles, the first tile is rotated 90 degrees from the other tiles, which otherwise are facing the correct direction.

**Comment by mclarkk** [comment]
I suspect your tile might be oriented 90 then. The orientation of the LIFX text on the back of the tile will show you which way the tile is rotated.

**Comment by CryptokidFH** [comment]
Don't you think the proper solution to this would have been making use of the accelerometer data that and correcting the orientation beforehand? Telling someone to just flip the tiles, especially with how much of a pain they are, seems like a pretty lame solution. Also why would you only just now comment and close this issue after 3 years?

________________________________

**Comment by mclarkk** [comment]
If the library currently supported accelerometer data and changing the orientation, I would definitely suggest that. However, adding those features isn't going to happen for a while, whereas rotating the tile could be done now. 

I started reading through issues today because some other projects that use lifxlan were breaking due to a critical but easily fixed problem. I'm currently finishing writing my dissertation, so I have just enough time to guiltily read through my backlog of lifxlan issues and hit low-hanging fruit, but I'm not available enough to add significant features. Gentle reminder that lifxlan is something I write and maintain for free. I'd love to work on it more, but sometimes we gotta work to eat.

**Comment by CryptokidFH** [comment]
Sorry my reply read the way it did, bad day. Is there a reason adding the accelerometer in won't happen for a while? Too low priority? I'm a recent CS student but graduated and looking for work so I have a lot of free time on my hands. I've only really poked around in your lib a few times but I honestly don't like python so I dropped it. That being said, I'm pretty bored all day, I could look in to it myself and make some pull requests if I ever get anywhere with it?

Again sorry for the reply earlier, shouldn't have taken that tone. I think I only made the issue in the first place because I wasn't sure if you weren't making use if the accelerometer data or because it was a bug with handling it.
________________________________

**Comment by mclarkk** [comment]
Yeah, it's too low priority (especially since the Tiles have been discontinued), and the redesign is trickier than it seems. Once accelerometer messages are supported, fixing your one case could be done quickly, but redesigning the library to gracefully support all the different possible rotation use cases out there would actually take quite a bit of thought. 

What if someone has tiles rotated 45 degrees (like a friend of mine does), or some arbitrary angle, how do you deal with rotating the matrix then? What if someone actually wants some of the animations rotated on some tiles, instead of corrected for gravity? Do you reference rotation angles to the Tile's actual orientation, or to the "gravity up" orientation? Does the Tile class do the rotations given some parameters, or does an outside utility operate on an input matrix and spit out the final matrix, which is then passed to the Tile class? And so on.

It's a bit of a design challenge to figure out what the right API is and which parts of the library should be responsible for what so that all the possible things people might want to do with rotations will be easy. However, If you'd like to take a crack at it and make a PR, I'd be happy to take a look! To start with, I would love it if you (or someone) could add accelerometer message support and add some kind of "get accelerometer reading" function for the Tiles. All possible redesigns will need to start from that base.

I hope your day gets better!
