### ISSUE TITLE
Most lights being detected but some of same model are not

### ISSUE THREAD

**Issue by Arndorferd** [mclarkk/lifxlan#169]
When I run

$ python3
>>> from lifxlan import *
>>> print(LifxLAN().get_lights())

10 lights get detected, 12 are on, 12 work with the lifx android app

The two lights that dont work the same model of light is being used in other places that do work.

**Comment by Arndorferd** [comment]
also lights show up in android app show up on child networks but lifxlan only shows 2 lights online on the child network and not the same 2 lights as the offline lights on parent network that dont work.

This doesnt make sense, I dont know why 2 lights would work on both networks but the rest all fail on one but not the parent. Yet 2 different ones fail on the parent network. Yet they all work on the android app.

**Comment by mclarkk** [comment]
Probably because the `products.py` file is out of date, though I can't confirm without knowing what model the missing lights are.

**Comment by HaberHash** [comment]
I'm having a similar issue.  I just got a couple of the new LIFX downlights can't discover them. Anyone know how to fix?   I've really been looking for something like this. I had Hue fixtures, which totally BLOW. I have 4 bridges and still can't get them running quick. I LOVE LIFX... just need to get them discovered.

Works with my old bulbs, but new bulbs can't be discovered. It's weird because I can issue set_color_all_lights and they'll all change.

**Comment by HaberHash** [comment]
I ended up using Photons, more specifically 'lifx lan:device_finder_info' to find details about my new lights then updated all of the products.py files across my system.  Seems to be working reasonably well so far.

**Comment by HaberHash** [comment]
FYI merged the products.py changes back here.
