### ISSUE TITLE
Getting status of individual bulb

### ISSUE THREAD

**Issue by nimonimonimo** [mclarkk/lifxlan#34]
Hi,

Thanks for writing lifxlan. I am currently playing around with it and trying to understand how to get the status of an individual bulb. Sending on and off works as expected, but it seems like it won't report status back unless I do full broadcast. Am I missing something?

```
#!/usr/bin/env python
from lifxlan import *
import sys
from time import sleep

def main():
    num_lights = None
    if len(sys.argv) != 3:
        print("\nDiscovery will go much faster if you provide the number of lights on your LAN:")
        print("  python {} <number of lights on LAN>\n".format(sys.argv[0]))
    else:
        ip = sys.argv[1]
        mac_address = sys.argv[2]

    print("IP: " + ip)
    print("MAC: " + mac_address)
    # instantiate LifxLAN client, num_lights may be None (unknown).
    # In fact, you don't need to provide LifxLAN with the number of bulbs at all.
    # lifx = LifxLAN() works just as well. Knowing the number of bulbs in advance
    # simply makes initial bulb discovery faster.
    #    print("Discovering lights...")
    #lifx = LifxLAN(1)

    # get devices
    bulb = Light(mac_address, ip)
    print(bulb.__dict__)
    bulb.set_power("on")
    print(bulb.__dict__)
    bulb.get_power()
```

**Comment by mclarkk** [comment]
Perhaps you forgot to `print(bulb.__dict__)` again after `bulb.get_power()`? When I print the dict after calling `bulb.get_power()` I see that the power_level goes from `'power_level': None` to `'power_level': 65535` (since my bulb is on), which is the expected behavior.

However, `__dict__` is a private variable for the bulb's internal bookkeeping that you should never have to access. The preferred way to get state, whether for power or color or anything else, would be to use a variable to store the return value of the function:

```
current_power = bulb.get_power()
print(current_power)
```

**Comment by nimonimonimo** [comment]
Embarrassingly enough it turns out it was a firewall issue, as I am running my bulbs on a separate vlan and as I thought that when settings power on/off worked that it then couldn't be a firewall issue, but surely enough it was that anyway.

**Comment by mclarkk** [comment]
Glad you figured it out!
