### ISSUE TITLE
Example of virtual bulb

### ISSUE THREAD

**Issue by nimonimonimo** [mclarkk/lifxlan#35]
Would it be possible for you to provide an example or more hints for how to build a virtual bulb that the LIFX  Android app would discover?

**Comment by mclarkk** [comment]
**Writing a virtual bulb that the official app will discover given the current public documentation is difficult to impossible.**

Once upon a time, I had a implementation for a virtual bulb that seemed like it should work but the LIFX app wasn't discovering it. Not only that, but the app was sending my virtual bulb several unknown message types. [I asked around on their developer forums](https://community.lifx.com/t/simulated-bulb-not-discovered-by-lifx-app/99) and they said that there were some messages that weren't documented yet. Unfortunately, if your virtual bulb doesn't know how to respond to these undocumented messages, then the app assumes the light is disconnected. Two out of the three unknown types have since been documented in the official protocol (51 is Device::GetGroup and 48 is Device::GetLocation), but one unknown message type (54) remains, and possibly more.

**Why are virtual bulbs useful anyway?**

Even though it's probably not yet possible to write a virtual light that the official app will recognize, it's certainly possible to write a virtual bulb that can be discovered and controlled by a program that uses lifxlan (or any other library that implements the LAN protocol, including those in other languages).

This means you could use a single main LIFX control program to interact with all your home lights at once, e.g. a single LIFX broadcast command could work on your Philips Hue bulbs via virtual LIFX bulbs as well as your native LIFX bulbs.

**How do you use virtual bulbs to control things like Hue lights?**

Say you have some Philips Hue lights in addition to LIFX lights. A virtual bulb in this case is a stand-alone program that acts as a LIFX driver for a Philips Hue light. These virtual bulbs would be always-on programs running on a Raspberry Pi or your home desktop or something, constantly listening for LIFX messages on your home network. Upon receiving LIFX messages that request information, the virtual bulb could send the appropriate LIFX message in response. Upon receiving LIFX command messages, the virtual bulb could control the Hue light they represent using a library like phue. 

**How do I get started writing a virtual bulb?**

Tragically, once I found out that the app would probably not be able to detect my virtual bulb, I apparently deleted `virtual_bulb.py` without ever checking it in. Whoops! To write your own, you'll need to implement [the four workflows documented by the LIFX LAN protocol](https://lan.developer.lifx.com/docs/workflow-diagrams).

Each workflow has slightly different behavior, but they will all require opening up a socket on the correct port and listen incoming UDP packets. Once you get a message, unpack it using unpack_lifx_message() from `unpack.py`. Pseudocode:

```
# see initialize_socket() in device.py for an example of how to open a socket on the right port
data, (ip_addr, port) = self.sock.recvfrom(1024) # listen for responses
request = unpack_lifx_message(data) # construct LIFX message from received data
```

The request variable now contains one of the LIFX message types in `msgtypes.py.` That means you can check the message type using the types listed in `msgtypes.py` and respond according to the four workflows:

```
if type(request) == GetService:
    #send back a StateService message
elif type(request) == SetLabel:
    new_label = request.label
    #set the label to be new_label, whatever that means to your virtual device
    if request.ack_requested == 1:
        #send Acknowledgement message with same source and sequence as request
    if request.response_requested == 1:
        #send StateLabel message containing the label in the payload with same source and sequence as request
elif type(request) == SetColor:
    ...
```

To see an example for how to send a certain LIFX message type with a specified payload, see the `fire_and_forget()` function in `device.py`.

That should help you get started! Let me know if you have any other questions.

**Comment by nimonimonimo** [comment]
Ah, thanks for your extensive reply. If it currently isn't possible to view the virtual bulb in the android app I will probably wait until that is possible.
