### ISSUE TITLE
Change from Port 56700?

### ISSUE THREAD

**Issue by autolog** [mclarkk/lifxlan#44]
Is it possible to get the LIFX devices to use a different port from 56700 in order to avoid conflicts with other apps using the same port?

The LIFX-LAN documentation implies that it is for non-version 1 lamps: 
[https://lan.developer.lifx.com/docs/device-messages#section-port](url)

I can't immediately figure out what would need changing.
Thanks for any help. :)

**Comment by mclarkk** [comment]
It doesn't look like you can change what port the bulbs are listening to. What you can change is the port that your _client_ is bound to. It looks like the difference between Version 1 and Version 2 firmware bulbs is that Version 2 bulbs will send their broadcast responses on the port of the client who sent the message (I think), whereas Version 1 bulbs will always send them on port 56700.

If you only have Version 2 bulbs and want to experiment with changing the client's port, you can go into `device.py` line 32 and change the `UDP_BROADCAST PORT` to a different one. That will change what port the client binds to, and therefore hopefully what port the lights will send broadcast responses to. However, the lights themselves may still be listening on 56700. You can check to see what port they're listening on by running the `hello_world.py` script in the examples.

**Comment by mclarkk** [comment]
Actually, hold up just a sec, the device methods need to be updated to use their port and not UDP_BROADCAST_PORT first.

**Comment by autolog** [comment]
Changing 56700 > 56705 results in no lamps being discovered. I am running lifxlan code in my Indigo plugin.

**Comment by mclarkk** [comment]
Ah, makes sense. How about change UDP_BROADCAST_PORT in device.py back to 56700, then change line 272 in lifxlan.py from `port = UDP_BROADCAST_PORT` to `port = 56705`. That ought to do it, my bad.

**Comment by autolog** [comment]
I have done that change and everything is working OK but I can't prove that it is using port 56705.
When I do a 'get_lights()' and print the returned devices, I get (one example):

> LIFX Infrared One
  MAC Address: d0:73:d5:20:b7:34
  IP Address: 192.168.1.79
  Port: 56700
  Service: UDP
  Power: On
  Location: 
  Group: 
  Color (HSBK): (64000, 0, 32112, 7000)
  Host Firmware Build Timestamp: 1479987403000000000 (2016-11-24 11:36:43 UTC)
  Host Firmware Build Version: 2.8
  Wifi Firmware Build Timestamp: 0 (1970-01-01 00:00:00 UTC)
  Wifi Firmware Build Version: 0.0
  Vendor: 1
  Product: 29 (LIFX+ A19)
  Version: 0
  Features: {'color': True, 'multizone': False, 'infrared': True}
  Current Time: 5676842712000000 (1970-03-07 16:54:02 UTC)
  Uptime (ns): 5676842712000000 (1576.9 hours)
  Last Downtime Duration +/-5s (ns): 0 (0.0 hours)
  Wifi Signal Strength (mW): 45.0
  Wifi TX (bytes): 2158002556
  Wifi RX (bytes): 2158002556

The port is still showing 57600. I know the change has worked because if I change the port to 576099 (too big) I get an error: 

> OverflowError: getsockaddrarg: port must be 0-65535.

Could it be that the wrong port number is being reported?

**Comment by mclarkk** [comment]
Nope! That's expected. 

There are a lot of parts of the LIFX system, and they each listen on their own ports. For example:

- The individual _lights_ listen on their own ports, and this you can't change. What the printout is showing you is the port that the light says it is listening on.

- The _client_, or program you're running to talk to the lights, also listens on a port in order to receive messages from the lights. You can change this port.

With the changes you made, your client program talks to the lights on whatever port they are listening on (which in this case is 56700), but listens for responses on port 56705, which is where the lights will now send their packets. (If they have Version 2 firmware, they will send both broadcast and unicast packets to that port, and if they have Version 1 firmware, they will only sent unicast packets there and broadcast packets will get sent to 56700.) Does that make sense?

**Comment by autolog** [comment]
That does make sense and will probably do what I want. I just wanted to listen for feedback from the lights on a different port i.e. Not 56700.
Thanks for taking the time to help.
It's much appreciated. 😃

**Comment by mclarkk** [comment]
Great! That should work then. Let me know if you have any other questions!

**Comment by autolog** [comment]
I am trying to work out what the code for method 'initialize_socket' in device.py (beginning at line 502) is doing. It seems if it can't get a port it tries the next one in sequence. Isn't this the broadcast port in which case the lamps won't see a command sent on a higher port number or have I misunderstood?

Also I am trying to figure out what the best way is to specify a port number in a calling program and pass the specified port number through such that it can be set in method 'initialize_socket' in lifxlan.py (at line 273) without having to hard code it in lifxlan.py.

Thanks for any pointers. :)

**Comment by mclarkk** [comment]
I'll give a more extensive reply in a bit, but quickly: a port is like a mailbox. When a client binds to a particular port and sends packets, it doesn't send packets _to_ that port, it send packets to whatever address and port it wants, and it _receives_ packets on its own port. The lamps will see the packets no matter what port the client binds to because the clients will send packets to the _lamps'_ ports. When the lamps get the packets from the client, those packets contain information about the client, including the client's port, so that's the port that the lamps send messages back to (both broadcast and unicast in the case of v2 bulbs).
