### ISSUE TITLE
Generation 3 Lights not discovering and cannot control them

### ISSUE THREAD

**Issue by dleffo** [mclarkk/lifxlan#52]
Appears that at the same time as the firmware update to 2.13 on the Generation 3 devices, I can no longer discover them with lifxlan.  Gen1 and 2 are still discovered ok.

Trying to toggle the power on a light by creating a bulb using:
bulb = Light(mac,ip)
 bulb.set_power("off",duration)

Gives the error:

  File "/usr/local/lib/python2.7/dist-packages/lifxlan/light.py", line 40, in get_power
    response = self.req_with_resp(LightGetPower, LightStatePower)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/device.py", line 490, in req_with_resp
    raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(self.mac_addr), str(self.label), str(msg_type)))
lifxlan.errors.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.LightStatePower'>] from d0:73:d5:20:67:a1 (Name: None) in response to <class 'lifxlan.msgtypes.LightGetPower'>

**Comment by mclarkk** [comment]
Have you tried power cycling the bulbs after the firmware update?

**Comment by mclarkk** [comment]
Upon [further reading](https://community.lifx.com/t/lifx-bulbs-not-seen-on-local-lan/1972/12), back in winter there was a release of Generation 3 firmware that caused incorrect behavior from the bulbs. The bulbs sent broadcast responses to the wrong port (the developers accidentally reversed the endianness of the port number, so it was going to 31965 instead of 56700). This only happened when the client set the source_id to 0, prompting a broadcast response from the bulb. If you set the source_id to any non-zero number, the bulb would sent a unicast response to the correct port. LIFX released new firmware to fix the problem in November/December, looks like. However, maybe the same thing happened again?

You can experiment to see if that's the problem by setting the source_id to a non-zero number when instantiating the bulb. For example:

```bulb = Light(mac, ip, service=1, port=56700, source_id=1337)```

It's a stretch to think that they made the same mistake again, but who knows! Worth a shot.

**Comment by amelchio** [comment]
I debugged this exact problem in aiolifx: frawau/aiolifx#10

**Comment by mclarkk** [comment]
@amelchio Can you explain what the problem was and why you think that's the problem here? It's not clear to me from the commit.

**Comment by mclarkk** [comment]
@dleffo I made the same changes to lifxlan's origin field check that @amelchio made in aiolifx. Pull, reinstall, and give it a try!

**Comment by dleffo** [comment]
Latest pull worked!  Thank you for such a quick response and the awesome code.

**Comment by mclarkk** [comment]
Great! I pushed a new version to PyPi! Many thanks to @amelchio!!!

**Comment by amelchio** [comment]
No, I cannot really explain it but I can see that my Gen2 bulbs have 1 in that field and Gen3 now has 0. Guess they just made their implementation match the documentation. As you said, there does not seem to be a reason to check the value so I just removed it.

It is you that should be thanked, I am only glad to help a little bit 😃
