### ISSUE TITLE
Simultaneous color change by group?

### ISSUE THREAD

**Issue by mfarley281** [mclarkk/lifxlan#55]
Apologies if this is the wrong forum in which to ask -- but I was wondering if anyone has figured out a way using this library to make synchronized changes across groups of lights?

In the cloud API you can send a command to a group and the change appears to be synchronized (e.g. all lights change at once).

With this library, I'm using asynchronous python to send a command to multiple bulbs in the same room at once, but you can easily see that the change doesn't take place fully in sync (some bulbs change quicker than others). I assume this is because there's no way in the library to address a "group" instead of a "device".

Has anyone found a clever way using this python library (or something similar on the LAN?) to send a change to multiple devices (e.g. group) and have it take place in sync on the lights?

Thanks!
Matt

**Comment by mclarkk** [comment]
There isn't a built-in method in the LAN protocol for changing groups simultaneously. According to the bottom of [this page](https://lan.developer.lifx.com/docs/groups-and-locations) of the official LIFX documentation: 

> To control a group of lights simultaneously simply message each member of the group individually using a unicast message.

What I would do if I were you is to set `rapid = True` for all of your individual commands. The `rapid` flag means that the program will send each light five duplicate packets (to protect against packet loss) and move on without waiting for a acknowledgement back from the light (that's where the slowdown happens). This approach is called "fire-and-forget." With `rapid = True`, the individual commands will work fast enough on each light that the changes will appear simultaneous. 

Let me know how that works for you. If you think that works well, I can add functionality to lifxlan to allow manipulation by group that uses `rapid = True` under the covers.

**Comment by dleffo** [comment]
I’ve used threading so that changing the bulb state runs in parallel.  I find the difference in timing to be imperceptible.  Would be faster I'm sure though if I didn't wait for the response.

Code snippet:
```
import thread
def toggle_power(bulb,power_state = "off", duration = 0):
    if power_state == "on":
        bulb.set_power("off",duration)
    else:
        bulb.set_power("on",duration)
```
Then in the main program:

`thread.start_new_thread(toggle_power,(bulb,power_state))`

**Comment by mclarkk** [comment]
At first I was hesitant to use threading because I wasn't sure how it would deal with multiple responses being received on the same port -- how would the program ensure that the right thread received the right packet? -- but I looked at the code again and each command opens up its own socket on a unique port, so each thread only receives responses to stuff that it has sent. Great! 

Threading definitely seems like the way to go when implementing groups. Thanks for trying it out and reporting back!

**Comment by mclarkk** [comment]
I just pushed a new update -- `lifxlan` now has a Group API! You can upgrade using pip or pull the changes and reinstall from source, depending on how you installed `lifxlan` originally. Sometimes the lights still change at visibly different times for some reason (maybe the Original bulbs I was testing on have internal processing time variability due to quirks of their design/firmware?), but in general it's a fairly synchronized effect -- definitely an improvement. Thanks again for the feedback!
