### ISSUE TITLE
Crash since 1.1.2 update - z lights

### ISSUE THREAD

**Issue by ceboxsell** [mclarkk/lifxlan#57]
Hello sorry to say that the Hello world example is showing errors now when listing lights.
Specifically the Z it seems as it was listing the original bulbs but not Z

`Traceback (most recent call last):
  File "c:/Python/lifxlan-master/examples/hello_world.py", line 30, in <module>
    main()
  File "c:/Python/lifxlan-master/examples/hello_world.py", line 27, in main
    print(d)
  File "C:\Python36\lib\site-packages\lifxlan\light.py", line 178, in __str__
    self.refresh()
  File "C:\Python36\lib\site-packages\lifxlan\device.py", line 93, in refresh
    self.location = self.get_location()
  File "C:\Python36\lib\site-packages\lifxlan\device.py", line 138, in get_location
    response = self.req_with_resp(GetLocation, StateLocation)
  File "C:\Python36\lib\site-packages\lifxlan\device.py", line 492, in req_with_resp
    raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(sel
f.mac_addr), str(self.label), str(msg_type)))
lifxlan.errors.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.StateLocation'>] from d0:73:d5:14:f0:a8 (Nam
e: None) in response to <class 'lifxlan.msgtypes.GetLocation'>`

**Comment by mclarkk** [comment]
`hello_world.py` works fine with my LIFX Z using the same setup (`lifxlan` version 1.1.2 with Python 3.6). WorkflowExceptions aren't usually caused by the library, but rather by the light being powered off, going offline, or otherwise not sending a response in time. It's hard to know what causes them sometimes, and they can come and go. If you're having consistent problems, I would try the following:

* Cut power to the light, then turn the power back on.
* Check for firmware updates.

Other folks have reported that this has helped fix similar issues. Let me know if this doesn't work!

**Comment by mclarkk** [comment]
Also, I see that you're on Windows. I just fixed a separate issue involving Windows discovery, so it might be a good idea to install the latest version and see if that helps.

**Comment by ceboxsell** [comment]
Thanks. Firstly on a new windows install on the weekend I could not discover any bulbs but on my tablet I still could find the 6 devices but then the error occurred.

I have seen the issues with the Z on my original one that LIFX replaced, after a while that one would respond to the broadcast so was counted but would not reply with all details causing the error. 

This issue with the Z was happening last night on the new install and my tablet no matter what I did, reboot unit, reboot AP reinstall etc.
Today from work over my VPN I am discovering the bulbs and listing the Z correctly so all seems to be working.  Fingers crossed the issue is resolved but I will try and replicate the issue at home tonight and hopefully this was all for nothing.

**Comment by ceboxsell** [comment]
Sorry to say, installed 1.1.3 and now no longer discovering bulbs. As I am behind the firewall I can't confirm till I get home but it was working just fine before updating.

**Comment by ceboxsell** [comment]
Found the problem for me on windows.
I have an old surface pro docked, the dock has a lan port but it is not used I am connected by WIFI.
As the LAN port was active the broadcast failed. Disabling the LAN port and all bulbs discovered correctly. The changes made in 1.1.3 were not needed it seems.

**Comment by mclarkk** [comment]
Good! I'm glad you figured out the problem. The 1.1.3 fixes were needed for Windows 10 installations (it fixed the problem you noticed of not being able to discover bulbs at all). However, it sounded like you also had a separate networking issue. The bulbs must be on the same subnet as the computer running the program for automatic discovery to work, since discovery is based on UDP broadcast. I'm glad you figured it out!
