### ISSUE TITLE
Issue when using direct Light object

### ISSUE THREAD

**Issue by bepsoccer** [mclarkk/lifxlan#69]
This used to work so I'm not entirely sure why it stopped.  When I create a Light object directly, the light api doesn't get responses.  If I discover lights they are Device objects and the light api works no problem.  Verbose output shows that device objects have the source_id set where as Light objects set this to 0.  Setting the source_id  in the Light class fixes this forcing the response back to unicast rather than broadcast.

**Comment by dleffo** [comment]
Confirm the same issue and workaround with the Lifx Mini.   Other products are otherwise working fine.

**Comment by mclarkk** [comment]
I fixed this! I left a long comment on pull request #70 explaining what was going on and how to best address it in a principled way. Long story short, I changed the code so that default source IDs are now set with the process ID of the program, so the default source_id is non-zero and all messages clearly come from the same client.

However, it does sound like the LIFX Mini firmware has a bug in it...
