### ISSUE TITLE
WorkflowException

### ISSUE THREAD

**Issue by Einstein42** [mclarkk/lifxlan#71]
Thanks for all your work on this project.

I wrote an interface to allow a home automation system to control the LiFX bulbs with your module. It works great most of the time, however quite often I get `WorkflowException: Did not receive [<class 'lifxlan.msgtypes.X'>]`

X obviously being the class type. 

I create a queue.Queue() for each device to make sure I don't send multiple commands to a device at a time. Also after discovery I create a class for each bulb and set `self.device = lifxlan.Light(self.mac, self.ip)` That way it has it's own direct connection. 

Then every 30 seconds I do three queries to each bulb. 

get_color / get_color_zones depending on if its a multizone bulb
get_power()
get_uptime()

About 10% (sometimes less, sometimes up to 50%) of the time, at least one of those fails. I've tried increasing your DEFAULT_TIMEOUT from your device class, I've tried time.sleep between calls, pretty much anything I can think of and no luck. I can't pin down to anything specific. I have a wifi router 5 feet from these bulbs (I've moved it further and closer to see if it made any difference). 

It's not a huge deal since I just query it again 30 seconds later, but I was hoping there might be something I'm doing wrong. 

Thanks for your time.

**Comment by mclarkk** [comment]
I'd be surprised if this is the problem, but you shouldn't need to create each Light object individually. The discovery function will return a list of Light/MultiZoneLight objects that were instantiated with the right IP and MAC addresses, so you can just iterate through that list. Unless you're doing something interesting with threads, I also don't see the need for a queue to prevent sending multiple commands to the lights, since the calls are blocking.

I made the following program to test for failures. It should be similar to yours, except that it queries every two seconds instead of every 30:

```
from lifxlan import *
from time import sleep

lan = LifxLAN()
bulbs = lan.get_lights()
while(True):
    for bulb in bulbs:
        try:
            label = bulb.get_label()
            color = None
            if bulb.supports_multizone():
                color = bulb.get_color_zones()
            elif bulb.supports_color():
                color = bulb.get_color()
            else:
                color = "Color not supported"
            power = bulb.get_power()
            uptime = bulb.get_uptime()
            print("{} {} {} {}".format(label, color, power, uptime))
        except WorkflowException as e:
            print(e)
    sleep(2)
```

After running this program for 10 minutes (300 loop iterations) I did not see any WorkflowExceptions*. I just merged several improvements to the networking part of the library, involving timeouts and direct vs. broadcast connections. It is possible that some of those fixed the issue -- if you pull and install the latest changes, do you see an improvement? (The latest changes are not yet available through pip.)

*Only two of my lights are in proper working order right now. For those two lights, I did not get any WorkflowExceptions. Two of my other lights have been experiencing chronic intermittent connection issues, which I can see in the LIFX app and which don't seem to be fixed through power cycling -- I haven't gotten around to figuring out what their problem is yet. In some runs where one of the misbehaving lights was picked up during discovery, I did get occasional WorkflowExceptions.
