### ISSUE TITLE
Fails to detect any devices on my network

### ISSUE THREAD

**Issue by assumptionsoup** [mclarkk/lifxlan#74]
It was working for about a week, and then everything stopped suddenly.  I'm not sure why.  I can't detect any lights on my network via lifxlan.  The official android app, and windows client can still detect lights.  I've tried lifxlan on windows 10 and ubuntu (arm64), neither are working anymore, while both were working a week ago.

**Comment by assumptionsoup** [comment]
Restarting my router seems to have fixed things for now.  What's really strange is that the official lifx apps were working while lifxlan wasn't.  I'll report back if this issue happens again.

**Comment by assumptionsoup** [comment]
It happened again.  I'm not quite sure where to start debugging this.  Any suggestions are appreciated.

**Comment by mclarkk** [comment]
A number of changes to the discovery process have been made in the last two months. I suspect some of the earlier changes borked your system, but if so, some of the most recent changes should have fixed it. Could you install the latest version of lifxlan and let me know whether or not you're still experiencing the problem?

One caveat: The install will need to be done from source (by cloning the repo (or updating it with `git pull`) and running `sudo python setup.py install`). PyPI is currently down due to spammers so I can't upload a new version to pip at the moment, but hopefully I'll be able to do that soon.

**Comment by mclarkk** [comment]
@assumptionsoup I want to ping you one more time to make sure the updates solved the problem. If I don't hear back soon, I'll close this issue due to inactivity and you can reopen it if it turns out to still be an issue!

**Comment by MaxValue** [comment]
Maybe my problem is related to this:

I upgraded from v 1.1.9 to v 1.2.2 and it didn't work anymore. I have to say that i do not use lifxlan to discover lights, only to issue commands in rapid mode (no confirmation required).

**Comment by assumptionsoup** [comment]
Thanks Mark!  I've been too busy to try this again.  I'll close this issue for now and reopen it if I have problems when I get back to this project.

**Comment by mclarkk** [comment]
Okay!! I hope it works out, I'd be happy to help troubleshoot. My name is Meghan :)

**Comment by assumptionsoup** [comment]
Oh, whoops! I don't know where I thought I saw mark!  Sorry!
